log:
  loglevel: info
dns:
  servers:
  - https+local://8.8.8.8/dns-query
inbounds:
- port: 8080
  protocol: trojan
  settings:
    clients:
    - password: "fdd10910-733d-40c6-9215-b745d05de0c9"
  streamSettings:
    network: ws
    wsSettings:
      path: qwe
  sniffing:
    enabled: false
    destOverride:
    - http
    - tls
    - quic
outbounds:
- protocol: freedom
  tag: direct
  settings:
    domainStrategy: UseIPv4
